- name: Instalar Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copiar página HTML de prueba
  copy:
    dest: /var/www/html/index.html
    content: "<h1>Servidor Web funcionando 🚀</h1>"

- name: Asegurar que Nginx esté activo
  service:
    name: nginx
    state: started
    enabled: true
