name: ISP Lab CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # ------------------------
  # 1. LINT & VALIDATION
  # ------------------------
  validate-dhcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Kea
        run: sudo apt-get update && sudo apt-get install -y kea-dhcp4-server kea-dhcp6-server
      - name: Validar Kea DHCPv4
        run: kea-dhcp4 -t -c ./configs/kea-dhcp4.conf
      - name: Validar Kea DHCPv6
        run: kea-dhcp6 -t -c ./configs/kea-dhcp6.conf

  validate-dns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar BIND9 utils
        run: sudo apt-get update && sudo apt-get install -y bind9-dnsutils bind9-utils
      - name: Validar named.conf
        run: named-checkconf ./configs/named.conf
      - name: Validar zona akranes.xyz
        run: named-checkzone akranes.xyz ./configs/zones/db.akranes.xyz

  validate-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Nginx
        run: sudo apt-get update && sudo apt-get install -y nginx
      - name: Validar config Nginx
        run: nginx -t -c $PWD/configs/nginx.conf

  validate-firewall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validar nftables
        run: sudo nft -c -f ./configs/nftables.conf

  # ------------------------
  # 2. UNIT TESTS
  # ------------------------
  test-dhcp:
    runs-on: ubuntu-latest
    services:
      kea:
        image: iscproject/kea-dhcp4
        volumes:
          - ./configs/kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Kea tools
        run: sudo apt-get update && sudo apt-get install -y kea-admin kea-common
      - name: Test con perfdhcp
        run: perfdhcp -4 -r 3 -n 3 127.0.0.1

  test-dns:
    runs-on: ubuntu-latest
    services:
      bind9:
        image: internetsystemsconsortium/bind9:9.18
        volumes:
          - ./configs/named.conf:/etc/bind/named.conf
          - ./configs/zones:/etc/bind/zones
        ports:
          - 53:53/udp
          - 53:53/tcp
    steps:
      - uses: actions/checkout@v3
      - name: Probar resoluci贸n DNS
        run: dig @127.0.0.1 akranes.xyz

  test-web:
    runs-on: ubuntu-latest
    services:
      web:
        image: nginx:stable
        volumes:
          - ./configs/nginx.conf:/etc/nginx/nginx.conf
          - ./www:/usr/share/nginx/html
        ports:
          - 80:80
    steps:
      - name: Probar webserver
        run: curl -I http://localhost | grep "200 OK"

  # ------------------------
  # 3. INTEGRATION TEST
  # ------------------------
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Levantar entorno integraci贸n
        run: docker-compose up -d
      - name: Esperar servicios
        run: sleep 15
      - name: Probar Web via Proxy
        run: curl -I http://localhost:8080 | grep "200 OK"
      - name: Probar DNS integraci贸n
        run: dig @127.0.0.1 web.akranes.xyz
      - name: Apagar entorno
        if: always()
        run: docker-compose down

  # ------------------------
  # 4. DEPLOY (solo en main)
  # ------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: [integration-test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: Desplegar en inventario de producci贸n
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
